apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-python-app
  template:
    metadata:
      labels:
        app: eks-python-app
    spec:
      containers:
      - name: eks-python-app
        image: 896406199305.dkr.ecr.us-east-1.amazonaws.com/eks-python-app:latest
        ports:
        - containerPort: 5000

